project:
  type: website
  output-dir: _site
  render:
    # https://quarto.org/docs/websites/#render-targets
    - "*.qmd"
    - "!ignored.qmd"
    - "!ignored-dir/"

website:  
  # johngavin.github.io/quarto-webr-pyodide-demo
  # quarto preview
  # quarto render 
  # gert::git_commit_all('quarto render not quarto preview')
  # gert::git_pull()
  # gert::git_push()
  repo-url: https://github.com/JohnGavin/quarto-webr-pyodide-demo
  # https://github.com/coatless-quarto/quarto-webr-pyodide-demo
  repo-actions: [edit, issue]
  title: "Quarto: webR & Pyodide"
  navbar:
    search: false
    left:
      - text: "Home"
        file: index.qmd
      - href: index.qmd
        text: "Homee"
      - text: "quarto-webr.qmd"
        file: quarto-webr.qmd
      - text: "quarto-pyodide.qmd"
        file: quarto-pyodide.qmd
      - text: "About - about.qmd"
      - about.qmd

#format:
#  html:
#    theme: cosmo
#    css: styles.css
#    toc: true